### ISSUE TITLE
How to do it more efficiently

### ISSUE THREAD

**Issue by AkashBonami** [AkashBonami/Pdf-Parser#2]
I need it to be better

**Comment by AryaShesham** [comment]
You simply have to look into your logical part and try to do it within the Time Complexity of O(n)

**Comment by AryaShesham** [comment]
> _No description provided._

You simply have to look into your logical part and try to do it within the Time Complexity of O(n)

**Comment by AkashBonami** [comment]
https://github.com/AkashBonami/Pdf-Parser/issues/2#issuecomment-1862169578
